### ISSUE TITLE
Kite connect trading and Historical API

### ISSUE THREAD

**Issue by sagar117** [PacktPublishing/Python-Algorithmic-Trading-Cookbook#1]
Do I need to have historical API subscribed in order to fetch information like circuits price, Buy/Sell market depth
I am trying to fetch market depth
`buy_market_depth, sell_market_depth = broker_connection.get_market_depth(instrument1)
print(f'Buy Market Depth:\n{buy_market_depth}')`

But getting invalid API key and secret

**Comment by guanidene** [comment]
I think you shouldn't require the historical data API.

The error you are suggesting tells me most likely the token was not generated correctly or has got expired.

**Comment by sagar117** [comment]
Yes, that was the issue thank you @guanidene 
Solved!
